import {
  ORDER_LIST_FAIL,
  ORDER_LIST_REQUEST,
  ORDER_LIST_SUCCESS,
} from "../constants/orderConstants";

export const ListOrderAction = () => async (dispatch) => {
  try {
    const data = [
      {
        id: 78341,
        itemName: "iPhone",
        price: 999.99,
        deliveredAt: "Dec, 2022",
        paymentMethod: "Credit Card",
        isPaid: false,
        shippingAddress: "2 main st, somewhere town",
        deliveryAddress: "123 Main St, Anytown, USA 12345",
        paidAt: "2022-11-30T23:59:59",
        category: "Smartphone",
      },
      {
        id: 16782,
        itemName: "MacBook Pro",
        price: 1499.99,
        deliveredAt: "Dec, 2022",
        paymentMethod: "PayPal",
        isPaid: true,
        shippingAddress: "2 main st, somewhere town",
        deliveryAddress: "456 Elm St, Anytown, USA 12345",
        paidAt: "2022-12-01T00:01:00",
        category: "Laptop",
      },
      {
        id: 45673,
        itemName: "Apple Watch",
        price: 399.99,
        deliveredAt: "Dec, 2022",
        paymentMethod: "Credit Card",
        isPaid: true,
        shippingAddress: "2 main st, somewhere town",
        deliveryAddress: "789 Oak Ave, Anytown, USA 12345",
        paidAt: "2022-11-30T12:34:56",
        category: "Wearable",
      },
      {
        id: 27894,
        itemName: "Samsung TV",
        price: 799.99,
        deliveredAt: "Apr, 2022",
        paymentMethod: "PayPal",
        isPaid: false,
        shippingAddress: "2 main st, somewhere town",
        deliveryAddress: "246 Birch Rd, Anytown, USA 12345",
        paidAt: "2022-12-01T01:23:45",
        category: "Television",
      },
      {
        id: 34615,
        itemName: "Amazon Echo",
        price: 99.99,
        deliveredAt: "Jun, 2022",
        paymentMethod: "Credit Card",
        isPaid: true,
        shippingAddress: "2 main st, somewhere town",
        deliveryAddress: "369 Maple Ln, Anytown, USA 12345",
        paidAt: "2022-11-30T23:59:59",
        category: "Smart Speaker",
      },
      {
        id: 16356,
        itemName: "Google Home",
        price: 79.99,
        deliveredAt: "Mar, 2022",
        paymentMethod: "PayPal",
        isPaid: true,
        shippingAddress: "2 main st, somewhere town",
        deliveryAddress: "159 Pine St, Anytown, USA 12345",
        paidAt: "2022-12-01T00:01:00",
        category: "Smart Speaker",
      },
      {
        id: 66097,
        itemName: "Fitbit Charge 4",
        price: 149.99,
        deliveredAt: "Sept, 2022",
        paymentMethod: "Credit Card",
        isPaid: true,
        shippingAddress: "2 main st, somewhere town",
        deliveryAddress: "753 Cedar Blvd, Anytown, USA 12345",
        paidAt: "2022-11-30T12:34:56",
        category: "Fitness Tracker",
      },
      {
        id: 90788,
        itemName: "Fitness Tracker",
        price: 99.99,
        deliveredAt: "Aug, 2022",
        paymentMethod: "Credit Card",
        isPaid: true,
        shippingAddress: "2 main st, somewhere town",
        deliveryAddress: "369 Cedar St, Anytown, USA 12345",
        paidAt: "2022-12-07T20:00:00",
        category: "Wearable Technology",
      },
      {
        id: 55679,
        itemName: "Wireless Earbuds",
        price: 79.99,
        deliveredAt: "Oct ,2022",
        paymentMethod: "PayPal",
        isPaid: true,
        shippingAddress: "2 main st, somewhere town",
        deliveryAddress: "159 Maple St, Anytown, USA 12345",
        paidAt: "2022-12-09T12:00:00",
        category: "Audio Devices",
      },
      {
        id: 23610,
        itemName: "Smart TV",
        price: 699.99,
        deliveredAt: "Nov, 2022",
        paymentMethod: "Credit Card",
        isPaid: true,
        shippingAddress: "2 main st, somewhere town",
        deliveryAddress: "753 Cherry St, Anytown, USA 12345",
        paidAt: "2022-12-11T15:00:00",
        category: "Television",
      },
      {
        id: 11096,
        itemName: "Tablet",
        price: 299.99,
        deliveredAt: "Jan, 2022",
        paymentMethod: "Credit Card",
        isPaid: true,
        shippingAddress: "2 main st, somewhere town",
        deliveryAddress: "789 Oak St, Anytown, USA 12345",
        paidAt: "2022-12-03T12:00:00",
        category: "Mobile Devices",
      },
    ];
    dispatch({ type: ORDER_LIST_REQUEST });
    dispatch({ type: ORDER_LIST_SUCCESS, payload: data });
  } catch (error) {
    dispatch({
      type: ORDER_LIST_FAIL,
      payload: "error",
      // error.response && error.response.data.message
      //   ? error.response.data.message
      //   : error.message,
    });
  }
};
